# -------------------------------
# user-defined configuration file
# -------------------------------
user_id: "bldelane" # CERN user ID for kinit @CERN.CH

# =============
# test-run flag
# =============
# if true, run pidcalib in `--test` mode
test: True
max_calib_files: 50 # how many calibration samples to run over in pidcalib [applies only if test is True]
# if true, produce all run info, including the path to calibration samples, TDirectiory and TTree
verbose: False 

# =======================
# pidcalib2 configuration - if in doubt: https://twiki.cern.ch/twiki/bin/view/LHCb/PIDCalibPackage#Which_variables_are_available_wi
# =======================
pid:
  # common to all particle species and years of data taking
  # NOTE: take care to specify ranges compatible with the data surviving the nominal event selection
  
  # alias : list[float, ...]
  binning:
    "Brunel_P"       : [10_000, 20_000, 30_000, 40_000, 50_000, 75_000, 100_000]
    "Brunel_ETA"     : [1.5, 2.5, 3.5, 4.5, 5.5]  
    "nTracks_Brunel" : [0, 150, 250, 1000] # checked that this is not used in any trigger/stripping cuts
  
  # what species are considered in the makeup of the misID?
  # NOTE: take care to specify the species alias employed in pidcalib2
  species: 
    kaon    : "K"
    pion    : "Pi"
    proton  : "P"
    electron: "e_B_Jpsi"
  
  # year-specific configuration
  years : ["2018"] 
  magpols : ["up"] # follow pidcalib2 syntax
  
  # PIDCALIB section: adopt pidcalib syntax to extract efficiencies from calibration data
  # -------------------------------------------------------------------------------------
  # muno-specific PID selection to isolate the single-track hadron-enriched data 
  antimu_id: 
    pid_cut: "_ProbNNghost<0.1 & DLLmu<0.0 & IsMuon==0.0 & probe_hasMuon==1.0 & InMuonAcc==1.0" # arg to `--pid_cut` option in pidcalib2

  # muon-specific PID selection in the signal-fit region  
  mu_id: 
    pid_cut: "_ProbNNghost<0.1 & DLLmu>3.0 & IsMuon==1.0 & probe_hasMuon==1.0 & InMuonAcc==1.0" # arg to `--pid_cut` option in pidcalib2 

  # selection shared between the hadron-enriched and signal samples. 
  # usually involving acceptance cuts, and the extrema of the mommentum range established in nominal events selection
  # for run 2 stripping vs turbo analyses, the `Brunel_` prefix might be required - see: https://twiki.cern.ch/twiki/bin/view/LHCb/PIDCalibPackage
  common_sel: "Brunel_P>10000 & Brunel_P<100000 & Brunel_PT>250" # NOTE: ensure the extrema are compatible with the binning json files

  # pidcalib cuts of HE sample to define the reco partitions
  reco_cuts:
    kaon_like      : "DLLK>0.0 & (DLLK-DLLp)>0.0 & (DLLK-DLLe)>0.0"
    pion_like      : "DLLK<0.0 & DLLp<0.0 & DLLe<0.0"
    proton_like    : "DLLp>0.0 & (DLLp-DLLK)>0.0 & (DLLp-DLLe)>0.0"
    electron_like  : "DLLe>0.0 & (DLLe-DLLK)>0.0 & (DLLe-DLLp)>0.0"
    # define `ghost-like` the partition evading all the above, in a slight abuse of notation
    ghost_like: "((DLLK < 0) | (DLLK == 0) | (DLLK - DLLp < 0) | (DLLK - DLLp == 0) | (DLLK - DLLe < 0) | (DLLK - DLLe == 0)) & ((DLLK > 0) | (DLLK == 0) | (DLLp > 0) | (DLLp == 0) | (DLLe > 0) | (DLLe == 0)) & ((DLLp < 0) | (DLLp == 0) | (DLLp - DLLK < 0) | (DLLp - DLLK == 0) | (DLLp - DLLe < 0) | (DLLp - DLLe == 0)) & ((DLLe < 0) | (DLLe == 0) | (DLLe - DLLK < 0) | (DLLe - DLLK == 0) | (DLLe - DLLp < 0) | (DLLe - DLLp == 0))"

  # ghosts section
  # --------------
  ghost_config: 
    path: "/ceph/submit/data/user/b/blaised/trex/hadron_enriched/butojpsik_mm_mc_MU_2018.root"
    key: ~
    tree: "DecayTree"
    # PID-less selection mimicking the hadron-enriched data selection -- PID excluded to be able to extract all necessary PID efficiencies 
    hadron_enriched_def_sel: "( Bplus_L0Global_TIS ) & \
      ( (Bplus_Hlt1TwoTrackMVADecision_TOS) | (Bplus_Hlt1TrackMVADecision_TOS) ) &\
      ( (Bplus_Hlt2Topo2BodyDecision_TOS) | (Bplus_Hlt2Topo3BodyDecision_TOS) ) & \
      ( (Kplus_LOKI_PP_InAccMuon==1.0) & (Kplus_PIDmu<0.0) & (Kplus_isMuon==0) & (Kplus_hasMuon==1.0) & (Kplus_ProbNNghost<0.1) ) & \
      ( (Kplus_PT>250) & (Kplus_P>10e3) & (Kplus_P<100e3) & (J_psi_1S_M>3096-50) & (J_psi_1S_M<3096+50) ) & \
      ( (Kplus_hasRich==1.0) & (Kplus_PIDK>-5.0) ) & \
      ( (Kplus_TRUEID==0) & (Bplus_TRUEID==0) & (Bplus_BKGCAT==60) )" # PDG numbering scheme and https://lhcb-doxygen.web.cern.ch/lhcb-doxygen/davinci/latest/df/d88/class_i_background_category.html for ghosts
    branch_prefix: "Kplus" # in converting the (anti)muon_id cuts above, I must establish the branch prefix for specific to the ghost ntuple


# =============================================================================================================================
# DATA section: cuts applied to the hadron enriched *data*: the syntax must reflect the branch names in the user-defined ntuple
# =============================================================================================================================
data: 
  input_path: "/ceph/submit/data/user/b/blaised/trex/hadron_enriched/butojpsik_mm_data_MU_2018.root" # path to hadron-enriched data file (pid + intermediate selection applied)
  output_path: "/ceph/submit/data/user/b/blaised/ddmisid/test/butojpsik_mm_data_MU_2018.root" # path to hadron-enriched data file (pid + intermediate selection applied)

  # prefix for muon branches in the data tuples
  data_prefixes: # NOTE: keys must match binning variable names
    P: "Kplus" # to signal that branches follow the naming convention Kplus_{P, PT, ETA...}
    ETA: "Kplus_LOKI"
    nTracks: ""

  root_config: # dependent on root file(s) of data being considered 
    root_key: ~
    root_tree_name: "DecayTree"

  # NOTE: follow awkward syntax: each selection cut enclosed by a set of brackets
  data_cuts: 
    kaon      : "(Kplus_LOKI_PP_InAccMuon==1.0) & (Kplus_P>10000) & (Kplus_P<100000) & (Kplus_PT>250) & (Kplus_PIDmu<0.0) & (Kplus_isMuon==0) & (Kplus_hasMuon==1.0) & (Kplus_ProbNNghost<0.1) & (Kplus_PIDK>0.0) & ( (Kplus_PIDK-Kplus_PIDp)>0.0 ) & ( (Kplus_PIDK-Kplus_PIDe)>0.0 )"
    pion      : "(Kplus_LOKI_PP_InAccMuon==1.0) & (Kplus_P>10000) & (Kplus_P<100000) & (Kplus_PT>250) & (Kplus_PIDmu<0.0) & (Kplus_isMuon==0) & (Kplus_hasMuon==1.0) & (Kplus_ProbNNghost<0.1) & (Kplus_PIDK<0.0) & (Kplus_PIDp<0.0) & (Kplus_PIDe<0.0)"
    proton    : "(Kplus_LOKI_PP_InAccMuon==1.0) & (Kplus_P>10000) & (Kplus_P<100000) & (Kplus_PT>250) & (Kplus_PIDmu<0.0) & (Kplus_isMuon==0) & (Kplus_hasMuon==1.0) & (Kplus_ProbNNghost<0.1) & (Kplus_PIDp>0.0) & ( (Kplus_PIDp-Kplus_PIDK)>0.0 ) & ( (Kplus_PIDp-Kplus_PIDe)>0.0 )"
    electron  : "(Kplus_LOKI_PP_InAccMuon==1.0) & (Kplus_P>10000) & (Kplus_P<100000) & (Kplus_PT>250) & (Kplus_PIDmu<0.0) & (Kplus_isMuon==0) & (Kplus_hasMuon==1.0) & (Kplus_ProbNNghost<0.1) & (Kplus_PIDe>0.0) & ( (Kplus_PIDe-Kplus_PIDK)>0.0 ) & ( (Kplus_PIDe-Kplus_PIDp)>0.0 )"
    # NOTE: I decided to absorb any residual candidates in the data in a `ghost` partition defined containing candidates evading the above; below, what I would write to match the string passed to pidcalib2. Both approaches yeild the same result as verified on 2018 MU data. 
    #ghost     : "(Kplus_InMuonAcc==1.0) & (Kplus_NShared==0) & (Kplus_P>10000) & (Kplus_P<100000) & (Kplus_PT>1500) & (Kplus_PIDmu<0.0) & (Kplus_isMuon==0) & (Kplus_hasMuon==1.0) & (Kplus_ProbNNghost<0.1) & ( ((Kplus_PIDK < 0) | (Kplus_PIDK == 0) | (Kplus_PIDK - Kplus_PIDp < 0) | (Kplus_PIDK - Kplus_PIDp == 0) | (Kplus_PIDK - Kplus_PIDe < 0) | (Kplus_PIDK - Kplus_PIDe == 0)) & ((Kplus_PIDK > 0) | (Kplus_PIDK == 0) | (Kplus_PIDp > 0) | (Kplus_PIDp == 0) | (Kplus_PIDe > 0) | (Kplus_PIDe == 0)) & ((Kplus_PIDp < 0) | (Kplus_PIDp == 0) | (Kplus_PIDp - Kplus_PIDK < 0) | (Kplus_PIDp - Kplus_PIDK == 0) | (Kplus_PIDp - Kplus_PIDe < 0) | (Kplus_PIDp - Kplus_PIDe == 0)) & ((Kplus_PIDe < 0) | (Kplus_PIDe == 0) | (Kplus_PIDe - Kplus_PIDK < 0) | (Kplus_PIDe - Kplus_PIDK == 0) | (Kplus_PIDe - Kplus_PIDp < 0) | (Kplus_PIDe - Kplus_PIDp == 0)) )"